---
title: "Example Dashboard Report"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
# load packages
library(flexdashboard)
library(tidyverse)
library(plotly)
library(DT)
library(leaflet)
library(viridis)

# load data
RawData <- read.csv("data/ExampleData (2).csv")
```

### Create a ggplotly object

```{r CreatePlotlyObject}
# use of ggplotly
AthleteSkilledPlot <- ggplot(RawData, aes(x = Limb, y = SkilledInvolvements)) +
  geom_jitter(aes(colour = Name)) +
  scale_colour_viridis_d() +
  geom_boxplot(alpha = 0.3) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 200)) +
  theme_classic()
# make an interactive plot
ggplotly(AthleteSkilledPlot)
```
### Create an interactive table uisng data table package 
```{r CreateDataTable}
# Create a table using the DT package
# First do some tidying
DataTidied <- RawData %>%
  group_by(Name, Limb) %>%
  summarise(Median = median(SkilledInvolvements), SD = sd(SkilledInvolvements, na.rm = FALSE)) %>%
  mutate(across(where(is.numeric), round, 1))
# call to the DT package
datatable(DataTidied, extensions = 'Buttons',
          options = list(dom = 'Bfrtip', buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))
```


### Chart B

```{r}

```

### Chart C

```{r}

```

